# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-02 15:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('accident_date', models.DateTimeField()),
                ('cause', multiselectfield.db.fields.MultiSelectField(choices=[('Alcohol', 'Alcohol'), ('Overspeeding', 'Overspeeding'), ('Driver distracted', 'Driver distracted'), ('Other', 'Other')], max_length=100)),
                ('persons', multiselectfield.db.fields.MultiSelectField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Child', 'Child'), ('Multiple', 'Multiple')], max_length=100)),
                ('description', models.TextField()),
                ('road', models.CharField(max_length=255)),
                ('categories', models.CharField(choices=[('Fatal', 'Fatal'), ('Serious', 'Serious'), ('Slight', 'Slight')], max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('registrations', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='accident',
            name='cars_involved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajali.Car'),
        ),
        migrations.AddField(
            model_name='accident',
            name='victims',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajali.Victim'),
        ),
    ]
