# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-02 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajali', '0002_auto_20180702_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.CharField(max_length=255),
        ),
    ]
