# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-04 11:52
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajali', '0004_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousReporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(blank=True, help_text='possible cause', max_length=255)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('accident_time', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'AnonymousReporter',
            },
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'County'},
        ),
    ]
