# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-04 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajali', '0005_auto_20180704_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousreporter',
            name='investigated',
            field=models.BooleanField(default=False),
        ),
    ]
